name:                pixelsort
version:             0.1.0.0
github:              "quasi-coherent/pixelsort"
license:             BSD3
author:              "Daniel Donohue"
maintainer:          "d.michael.donohue@gmail.com"
copyright:           "2019 Daniel Donohue"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/quasi-coherent/pixelsort#readme>

executables:
  pixelsort:
    main: Main.hs
    source-dirs: .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - bytestring
    - JuicyPixels
    - lens
    - optparse-applicative
    - vector
    - vector-algorithms
